[package]
name = "morse2sound"
version = "0.1.0"
authors = ["irevenko <ilya.revenko17@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
rodio = "0.13.0"
structopt = "0.3.21"
